"""added alpha-2 code for currency

Revision ID: 0342e3170f2c
Revises: 9385cd10423a
Create Date: 2024-02-27 21:47:00.649717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0342e3170f2c'
down_revision = '9385cd10423a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_column('flag')

    with op.batch_alter_table('currency', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alpha_2_code', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currency', schema=None) as batch_op:
        batch_op.drop_column('alpha_2_code')

    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag', sa.VARCHAR(length=5), nullable=True))

    # ### end Alembic commands ###
