"""empty message

Revision ID: 0830513e7478
Revises: 913d6042932d
Create Date: 2024-03-24 19:57:11.875813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0830513e7478'
down_revision = '913d6042932d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('second_cur', sa.String(length=3), nullable=True))
        batch_op.alter_column('default_cur',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
        batch_op.create_foreign_key('user_2nd_currency_fk', 'currency', ['second_cur'], ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_2nd_currency_fk', type_='foreignkey')
        batch_op.alter_column('default_cur',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
        batch_op.drop_column('second_cur')

    # ### end Alembic commands ###
