"""added fav_curs for user

Revision ID: 22813b679864
Revises: 0830513e7478
Create Date: 2024-03-28 17:18:09.091807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22813b679864'
down_revision = '0830513e7478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fav_curs', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fav_curs')

    # ### end Alembic commands ###
