"""Added nationality and currency field in user sign up field

Revision ID: 849cdbf94ec1
Revises: cd25c1820d0c
Create Date: 2024-02-08 19:05:09.884792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849cdbf94ec1'
down_revision = 'cd25c1820d0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_cur', sa.String(length=3), nullable=True))
        batch_op.create_foreign_key('user_currency_fk', 'currency', ['default_cur'], ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_currency_fk', type_='foreignkey')
        batch_op.drop_column('default_cur')

    # ### end Alembic commands ###
