"""Added flag for country

Revision ID: 8a6464a8d638
Revises: d578e671b3b5
Create Date: 2024-02-02 14:23:38.342372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a6464a8d638'
down_revision = 'd578e671b3b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag', sa.String(length=5), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.drop_column('flag')

    # ### end Alembic commands ###
