"""added is_enabled to notification

Revision ID: 913d6042932d
Revises: e88a70c5cf59
Create Date: 2024-03-05 22:07:24.179206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913d6042932d'
down_revision = 'e88a70c5cf59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('is_enabled')

    # ### end Alembic commands ###
