"""Added nationality field in user sign up field

Revision ID: 9385cd10423a
Revises: 849cdbf94ec1
Create Date: 2024-02-08 19:09:33.968948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9385cd10423a'
down_revision = '849cdbf94ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nationality', sa.String(length=3), nullable=True))
        batch_op.create_foreign_key('user_country_fk', 'country', ['nationality'], ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_country_fk', type_='foreignkey')
        batch_op.drop_column('nationality')

    # ### end Alembic commands ###
