"""relate user  to notification model

Revision ID: a63f45777a61
Revises: f5fc84fc9775
Create Date: 2024-04-13 00:59:18.013353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a63f45777a61'
down_revision = 'f5fc84fc9775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_notification_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notification_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
