"""changed notiifcation to alert and added indicator col

Revision ID: b957023e8c29
Revises: 22813b679864
Create Date: 2024-04-11 17:39:30.035828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b957023e8c29'
down_revision = '22813b679864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_from_cur_code')
        batch_op.drop_index('ix_notification_to_cur_code')
        batch_op.drop_index('ix_notification_user_id')

    op.drop_table('notification')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('alert_type', sa.VARCHAR(length=13), nullable=False),
    sa.Column('period', sa.VARCHAR(length=5), nullable=True),
    sa.Column('condition', sa.VARCHAR(length=4), nullable=True),
    sa.Column('rate', sa.FLOAT(), nullable=True),
    sa.Column('notify_in_app', sa.BOOLEAN(), nullable=True),
    sa.Column('notify_email', sa.BOOLEAN(), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=255), nullable=True),
    sa.Column('from_cur_code', sa.VARCHAR(length=3), nullable=False),
    sa.Column('to_cur_code', sa.VARCHAR(length=3), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['from_cur_code'], ['currency.code'], ),
    sa.ForeignKeyConstraint(['to_cur_code'], ['currency.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='notification_user_fk'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index('ix_notification_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_notification_to_cur_code', ['to_cur_code'], unique=False)
        batch_op.create_index('ix_notification_from_cur_code', ['from_cur_code'], unique=False)

    # ### end Alembic commands ###
