"""Added currency table and linked currency code as foreign key in country

Revision ID: c94f0dc42034
Revises: bd3c7e6c4832
Create Date: 2024-02-02 22:18:02.304182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c94f0dc42034'
down_revision = 'bd3c7e6c4832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_country_currency', 'currency', ['currency_code'], ['code'])
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_country_currency', type_='foreignkey')

    # ### end Alembic commands ###
