"""Changed condition for currency_code in country table

Revision ID: cd25c1820d0c
Revises: c94f0dc42034
Create Date: 2024-02-02 23:12:31.750227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd25c1820d0c'
down_revision = 'c94f0dc42034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_country_currency_code'), ['currency_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_country_currency_code'))

    # ### end Alembic commands ###
