"""changed datatypes to enum and added rsi_val to alert table

Revision ID: e3faab40cfab
Revises: b957023e8c29
Create Date: 2024-04-11 17:47:49.622776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3faab40cfab'
down_revision = 'b957023e8c29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rsi_val', sa.Float(), nullable=True))
        batch_op.alter_column('alert_type',
               existing_type=sa.VARCHAR(length=13),
               nullable=True)
        batch_op.alter_column('period',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('daily', 'weekly', 'monthly', name='period_enum'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.alter_column('period',
               existing_type=sa.Enum('daily', 'weekly', 'monthly', name='period_enum'),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
        batch_op.alter_column('alert_type',
               existing_type=sa.VARCHAR(length=13),
               nullable=False)
        batch_op.drop_column('rsi_val')

    # ### end Alembic commands ###
