"""linked notification to user

Revision ID: e88a70c5cf59
Revises: 0342e3170f2c
Create Date: 2024-03-04 04:17:42.823821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e88a70c5cf59'
down_revision = '0342e3170f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('notification_user_fk', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint('notification_user_fk', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
